/* ============================================================
   build.mjs —— 线上版构建脚本
   作用：把带注释的开发版站点压缩后输出到 dist/
     - HTML：移除注释、折叠空白、压缩内联 CSS/JS；
             标题 / meta description 按 site-config.json 注入
     - CSS：clean-css 压缩（assets/css/*.css）
     - JS ：terser 压缩并移除注释（assets/js/*.js）
     - applications/ 与 posts/*.html 原样复制（后台「整段编辑代码
       /文章」读到的内容必须与仓库逐字一致，故不做压缩）
     - JSON、SVG、图片等资源原样复制（保留 _comment 注释字段）
   GitHub Actions 会在 push 到 main 时自动执行本脚本。
   ============================================================ */

import fs from 'node:fs';
import path from 'node:path';
import { minify as minifyHtml } from 'html-minifier-terser';
import CleanCSS from 'clean-css';
import { minify as minifyJs } from 'terser';

const ROOT = process.cwd();
const DIST = path.join(ROOT, 'dist');

/* 递归删除旧产物 */
fs.rmSync(DIST, { recursive: true, force: true });

function ensureDir(file) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function writeFile(file, content) {
  ensureDir(file);
  fs.writeFileSync(file, content);
}

function copyFile(src, dest) {
  ensureDir(dest);
  fs.copyFileSync(src, dest);
}

/* 遍历目录，返回全部文件相对路径 */
function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full).map((p) => path.join(entry.name, p)));
    } else {
      out.push(entry.name);
    }
  }
  return out;
}

function escHtml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/* 站点配置：用于注入 <title> 与 meta description（静态兜底，
   前台 JS 运行后还会按配置再设一次 document.title） */
var siteConfig = {};
try {
  siteConfig = JSON.parse(fs.readFileSync(path.join(ROOT, 'site-config.json'), 'utf8'));
} catch (e) {
  console.warn('  [warn] site-config.json 读取失败，跳过标题注入');
}
const siteName = siteConfig.siteName || 'My Blog';
const siteDesc = String(siteConfig.description || '').trim();

/* 页面标题：文件名 → 完整 title */
const PAGE_TITLES = {
  'index.html': siteName,
  'page.html': siteName,
  '404.html': '404 - 页面走丢了'
};

/* 注入/替换 <title> 与 meta description（压缩前处理，源码保持可读） */
function injectMeta(html, title) {
  let out = html.replace(/<title>[\s\S]*?<\/title>/i, '<title>' + escHtml(title) + '</title>');
  if (siteDesc) {
    const tag = '<meta name="description" content="' + escHtml(siteDesc) + '">';
    if (/<meta[^>]+name=["']description["'][^>]*>/i.test(out)) {
      out = out.replace(/<meta[^>]+name=["']description["'][^>]*>/i, tag);
    } else {
      out = out.replace(/<\/head>/i, '  ' + tag + '\n</head>');
    }
  }
  return out;
}

const htmlOptions = {
  collapseWhitespace: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  useShortDoctype: true,
  minifyCSS: true,
  minifyJS: true,
  includeAutoGeneratedTags: false
};

const cssMinifier = new CleanCSS({ level: 2 });

async function build() {
  const tasks = [];

  function addHtml(rel, title) {
    tasks.push(
      fs.promises.readFile(path.join(ROOT, rel), 'utf8')
        .then((code) => injectMeta(code, title || PAGE_TITLES[rel] || siteName))
        .then((code) => minifyHtml(code, htmlOptions))
        .then((out) => writeFile(path.join(DIST, rel), out))
        .then(() => console.log('  html  ', rel))
    );
  }

  /* 1. 根目录外壳页（压缩 + 标题/描述注入）：
     index=落地页，page=所有动态页共用的渲染器，404=GitHub Pages 约定 */
  ['index.html', 'page.html', '404.html'].forEach((n) => addHtml(n));

  /* 2. 后台页面（压缩；不注入站点标题） */
  tasks.push(
    fs.promises.readFile(path.join(ROOT, 'admin/index.html'), 'utf8')
      .then((code) => minifyHtml(code, htmlOptions))
      .then((out) => writeFile(path.join(DIST, 'admin/index.html'), out))
      .then(() => console.log('  html  ', 'admin/index.html'))
  );

  /* 3. CSS（压缩） */
  for (const name of walk('assets/css')) {
    if (!name.endsWith('.css')) continue;
    const src = path.join(ROOT, 'assets/css', name);
    const result = cssMinifier.minify(fs.readFileSync(src, 'utf8'));
    if (result.errors.length) {
      throw new Error('CSS 压缩失败 ' + name + ': ' + result.errors.join('; '));
    }
    writeFile(path.join(DIST, 'assets/css', name), result.styles);
    console.log('  css   ', 'assets/css/' + name);
  }

  /* 4. assets/js（terser 压缩去注释） */
  for (const name of walk('assets/js')) {
    if (!name.endsWith('.js')) continue;
    tasks.push(
      (async () => {
        const src = path.join(ROOT, 'assets/js', name);
        const result = await minifyJs(fs.readFileSync(src, 'utf8'), {
          format: { comments: false }
        });
        writeFile(path.join(DIST, 'assets/js', name), result.code || '');
        console.log('  js    ', 'assets/js/' + name);
      })()
    );
  }

  /* 5. applications/ 整个目录原样复制（.js 不压缩：后台整段代码编辑
        必须读到与仓库逐字一致、带注释的原文，同 posts 策略） */
  for (const name of walk('applications')) {
    copyFile(path.join(ROOT, 'applications', name), path.join(DIST, 'applications', name));
    console.log('  copy  ', 'applications/' + name);
  }

  /* 6. posts/ 目录：文章 HTML 与本地查看页原样复制，不做任何压缩处理 */
  for (const name of walk('posts')) {
    copyFile(path.join(ROOT, 'posts', name), path.join(DIST, 'posts', name));
    console.log('  copy  ', 'posts/' + name);
  }

  /* 7. assets 静态资源：图片 / 站点图标 / 壁纸 SVG / 背景视频 / favicon 原样复制。
        videos 目录暂可不存在，walk 对缺失目录安全返回空数组 */
  for (const sub of ['images', 'icons', 'wallpapers', 'videos']) {
    for (const name of walk(path.join('assets', sub))) {
      copyFile(path.join(ROOT, 'assets', sub, name), path.join(DIST, 'assets', sub, name));
      console.log('  copy  ', 'assets/' + sub + '/' + name);
    }
  }
  copyFile(path.join(ROOT, 'assets/favicon.svg'), path.join(DIST, 'assets/favicon.svg'));
  console.log('  copy  ', 'assets/favicon.svg');

  /* 8. 数据文件：根目录只保留 site-config.json，其余数据 JSON 都在 data/，
        全部原样复制（保留可读格式与 _comment 字段）。
        注意：根目录 package.json 是构建工具配置，不部署 */
  copyFile(path.join(ROOT, 'site-config.json'), path.join(DIST, 'site-config.json'));
  console.log('  copy  ', 'site-config.json');
  for (const name of walk('data')) {
    copyFile(path.join(ROOT, 'data', name), path.join(DIST, 'data', name));
    console.log('  copy  ', 'data/' + name);
  }

  /* 9. robots.txt 原样复制 */
  copyFile(path.join(ROOT, 'robots.txt'), path.join(DIST, 'robots.txt'));
  console.log('  copy  ', 'robots.txt');

  await Promise.all(tasks);
  console.log('\n构建完成 → dist/');
}

build().catch((err) => {
  console.error('构建失败：', err);
  process.exit(1);
});
